# Generated by Django 3.2.5 on 2021-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=30)),
                ('project_about', models.CharField(max_length=30)),
                ('project_description', models.CharField(max_length=2000)),
                ('screen_shot', models.ImageField(upload_to='')),
            ],
        ),
    ]
