# Generated by Django 3.2.5 on 2021-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='languages',
            field=models.CharField(choices=[('django', 'django'), ('Flask', 'Flask'), ('Angular', 'Angular'), ('Javascript', 'Javascript'), ('Python', 'Python'), ('C#', 'C#'), ('Java', 'Java'), ('C', 'C'), ('Swift', 'Swift')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.CharField(choices=[('django', 'django'), ('Flask', 'Flask'), ('Angular', 'Angular'), ('Javascript', 'Javascript'), ('Python', 'Python'), ('C#', 'C#'), ('Java', 'Java'), ('C', 'C'), ('Swift', 'Swift'), ('git', 'git'), ('postgresql', 'postgresql'), ('bootstrap', 'bootstrap')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
