# Generated by Django 3.2.5 on 2021-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='technologies',
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
