# Generated by Django 3.2.5 on 2021-07-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210717_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='screen_shot',
            field=models.ImageField(default='Image', upload_to='images/'),
        ),
    ]
