# Generated by Django 3.2.5 on 2021-07-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projects_screen_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='Image', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='screen_shot',
            field=models.ImageField(default='Image', upload_to='image'),
        ),
    ]
