# Generated by Django 3.2.5 on 2021-07-18 22:10

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='screen_shot',
            field=cloudinary.models.CloudinaryField(default='Image', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
    ]
