# Generated by Django 3.2.5 on 2021-07-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210719_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='technologies',
            field=models.CharField(max_length=200),
        ),
    ]
