# Generated by Django 3.2.5 on 2021-07-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projects_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project_id',
        ),
    ]
