# Generated by Django 3.2.5 on 2021-07-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_review_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
            preserve_default=False,
        ),
    ]
