# Generated by Django 3.2.5 on 2021-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_link',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
